#!/bin/sh

build() {
    add_all_modules "/char/tpm/"
    add_binary "bash"
    add_binary "tr"
    add_binary "grep"
    add_binary "sed"
    add_binary "curl"

    for _LIBRARY in /usr/bin/clevis* /usr/bin/tpm2*; do
        add_binary "${_LIBRARY}"
    done

    add_binary "jose"
    add_binary "luksmeta"

    for _LIBRARY in /usr/lib/libtss2-tcti-device.so*; do
        if [ -e "${_LIBRARY}" ]; then
            add_binary "${_LIBRARY}"
        fi
    done

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows decryption of multiple LUKS devices automatically via
clevis/TPM and/or by passphrase. To use, add kernel parameters with the format
'cryptdevice=DEVICE:NAME:OPTIONS' for each device to be unlocked. For example,

cryptdevice=PARTUUID=22ea7485-1688-48ef-83c8-452feb21d18b:root:discard

Options may be left blank and currently the only supported option is discard.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
